// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhebfxfdepieptmpnmms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oZWJmeGZkZXBpZXB0bXBubW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTQ1MDcsImV4cCI6MjA2ODY5MDUwN30.hT4KGzxdSzSw8F3IbLp7YUq9lOc4FZUL7bBcFIR3meQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});